### ISSUE TITLE
Where should we write OpenCV code in C++?

### ISSUE THREAD

**Issue by rezaee** [makbn/OpenCV_sample_android_studio#1]
I tried your tutorial but after all, where should I write and test OpenCV code ?

**Comment by makbn** [comment]
look at my code:
https://github.com/makbn/opencv_android_setup_tutorial/tree/master/app/src/main
I put cpp & h files in cpp folder!

you can find some good practice here: 
https://github.com/opencv/opencv/tree/master/samples/android
